<a href="https://colab.research.google.com/github/sunnysavita10/Indepth-GENAI/blob/main/Reranking_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
documents = [
    "This is a list which containing sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings.",
    "Understanding document structure aids in keyword extraction.",
    "Efficient keyword extraction enhances search accuracy.",
    "Semantic similarity improves document retrieval performance.",
    "Machine learning algorithms can optimize keyword extraction methods."
]

In [2]:
!pip install sentence_transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.1/227.1 kB 1.6 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-m

In [5]:
from sentence_transformers import SentenceTransformer

/usr/local/lib/python3.10/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


In [6]:
# Load pre-trained Sentence Transformer model
model_name = 'sentence-transformers/paraphrase-xlm-r-multilingual-v1'

In [7]:
model = SentenceTransformer(model_name)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.78k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/718 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/550 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [10]:
documents

['This is a list which containing sample documents.',
 'Keywords are important for keyword-based search.',
 'Document analysis involves extracting keywords.',
 'Keyword-based search relies on sparse embeddings.',
 'Understanding document structure aids in keyword extraction.',
 'Efficient keyword extraction enhances search accuracy.',
 'Semantic similarity improves document retrieval performance.',
 'Machine learning algorithms can optimize keyword extraction methods.']

In [11]:
len(documents)

8

In [8]:
document_embeddings = model.encode(documents)

In [12]:
len(document_embeddings)

8

In [13]:
len(document_embeddings[0])

768

In [9]:
for i, embedding in enumerate(document_embeddings):
    print(f"Document {i+1} embedding: {embedding}")

Document 1 embedding: [ 0.10894686  0.07812074  0.11626554 -0.3191249   0.46890235  0.4351442
  0.01453751  0.44238743  0.29716408 -0.18982704  0.07389083 -0.27864912
  0.21338145 -0.12077019  0.17891686 -0.00789894  0.0475487  -0.18204558
  0.34227124 -0.06994265 -0.14288713  0.5714126  -0.11153252 -0.178954
  0.0152314   0.26105717 -0.20555818  0.05203104 -0.02810767  0.23873205
  0.01206982  0.0440495   0.02242325 -0.13895164 -0.7410038   0.2560102
  0.08149666  0.18820472 -0.41237685  0.11368611  0.28121182  0.05860903
 -0.17318785  0.33549157  0.21803693 -0.05090728 -0.05457798 -0.8738478
 -0.24082269  0.3200701   0.44761682  0.06347839  0.53574854  0.16607253
 -0.33197004  0.33393636  0.28615928 -0.5419567  -0.27132416  0.24881189
 -0.2391937  -0.46926293  0.13836566  0.3784288  -0.01304432  0.01990609
  0.323651    0.45857546  0.07600272  0.25299594 -0.42938972  0.10051935
 -0.33042622 -0.69876486  0.01035881  0.05666538  0.14731242 -0.47082362
  0.08064     0.3387045  -0.272781

In [14]:
documents

['This is a list which containing sample documents.',
 'Keywords are important for keyword-based search.',
 'Document analysis involves extracting keywords.',
 'Keyword-based search relies on sparse embeddings.',
 'Understanding document structure aids in keyword extraction.',
 'Efficient keyword extraction enhances search accuracy.',
 'Semantic similarity improves document retrieval performance.',
 'Machine learning algorithms can optimize keyword extraction methods.']

In [16]:
query = "Natural language processing techniques enhance keyword extraction efficiency."

In [17]:
query_embedding = model.encode(query)

In [18]:
print("Query embedding:", query_embedding)

Query embedding: [ 3.42821181e-01  3.26170564e-01  7.73251383e-03  1.60759035e-02
  2.38518156e-02 -2.52880514e-01  8.15469772e-02  1.37177318e-01
  3.33291799e-01  3.65743041e-02 -9.28227529e-02 -3.43726009e-01
  7.12015256e-02  9.48833704e-01 -9.41289738e-02 -7.96414435e-01
 -3.20592433e-01 -2.67564565e-01  2.08664417e-01  7.99598247e-02
  7.93347415e-03 -5.22295274e-02 -1.00512497e-01 -2.04229861e-01
  2.19562605e-01  7.67739043e-02  1.25881582e-01  2.90843934e-01
 -4.99190986e-01  2.27709264e-01 -1.94742545e-01  7.21396282e-02
 -4.56500938e-03  1.21945657e-01 -1.46225825e-01 -9.64743719e-02
  1.02258191e-01 -2.04421282e-01 -3.95658046e-01  7.32254162e-02
  1.10103995e-01  4.84611303e-01  1.04519367e-01  3.86131942e-01
 -1.68697596e-01 -2.11251289e-01 -6.38036489e-01 -4.32641655e-01
  2.74459004e-01  9.64056328e-02 -1.30053475e-01  5.76567650e-02
  8.07964280e-02  6.48148209e-02 -2.14203727e-03  2.29773983e-01
 -6.66051432e-02  3.07675213e-01  2.11779296e-01 -1.57844439e-01
  9.7885

In [22]:
len(query_embedding)

768

In [19]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [20]:
similarities = cosine_similarity(np.array([query_embedding]), document_embeddings)

In [21]:
similarities

array([[0.16948138, 0.45802268, 0.56756926, 0.44123274, 0.6316117 ,
        0.7521413 , 0.5503519 , 0.74481654]], dtype=float32)

In [23]:
most_similar_index = np.argmax(similarities)

In [24]:
most_similar_index

5

In [25]:
most_similar_document = documents[most_similar_index]

In [26]:
most_similar_document

'Efficient keyword extraction enhances search accuracy.'

In [27]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [28]:
similarity_score = similarities[0][most_similar_index]

In [29]:
similarity_score

0.7521413

In [61]:
sorted_indices = np.argsort(similarities[0])[::-1]

In [31]:
sorted_indices

array([5, 7, 4, 2, 6, 1, 3, 0])

In [32]:
ranked_documents = [(documents[i], similarities[0][i]) for i in sorted_indices]

In [33]:
ranked_documents

[('Efficient keyword extraction enhances search accuracy.', 0.7521413),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  0.74481654),
 ('Understanding document structure aids in keyword extraction.', 0.6316117),
 ('Document analysis involves extracting keywords.', 0.56756926),
 ('Semantic similarity improves document retrieval performance.', 0.5503519),
 ('Keywords are important for keyword-based search.', 0.45802268),
 ('Keyword-based search relies on sparse embeddings.', 0.44123274),
 ('This is a list which containing sample documents.', 0.16948138)]

In [34]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [35]:
print("Ranked Documents:")
for rank, (document, similarity) in enumerate(ranked_documents, start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Ranked Documents:
Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.7521412968635559
Rank 2: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.7448165416717529
Rank 3: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.631611704826355
Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.5675692558288574
Rank 5: Document - 'Semantic similarity improves document retrieval performance.', Similarity Score - 0.5503519177436829
Rank 6: Document - 'Keywords are important for keyword-based search.', Similarity Score - 0.45802268385887146
Rank 7: Document - 'Keyword-based search relies on sparse embeddings.', Similarity Score - 0.44123274087905884
Rank 8: Document - 'This is a list which containing sample documents.', Similarity Score - 0.16948138177394867


In [36]:
print("Top 4 Documents:")
for rank, (document, similarity) in enumerate(ranked_documents[:4], start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Top 4 Documents:
Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.7521412968635559
Rank 2: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.7448165416717529
Rank 3: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.631611704826355
Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.5675692558288574


In [39]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [37]:
!pip install rank_bm25

In [38]:
from rank_bm25 import BM25Okapi

In [40]:
top_4_documents = [doc[0] for doc in ranked_documents[:4]]

In [41]:
top_4_documents

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [42]:
tokenized_top_4_documents = [doc.split() for doc in top_4_documents]

In [43]:
tokenized_top_4_documents

[['Efficient', 'keyword', 'extraction', 'enhances', 'search', 'accuracy.'],
 ['Machine',
  'learning',
  'algorithms',
  'can',
  'optimize',
  'keyword',
  'extraction',
  'methods.'],
 ['Understanding',
  'document',
  'structure',
  'aids',
  'in',
  'keyword',
  'extraction.'],
 ['Document', 'analysis', 'involves', 'extracting', 'keywords.']]

In [44]:
tokenized_query = query.split()

In [45]:
tokenized_query

['Natural',
 'language',
 'processing',
 'techniques',
 'enhance',
 'keyword',
 'extraction',
 'efficiency.']

In [46]:
bm25=BM25Okapi(tokenized_top_4_documents)

In [47]:
bm25

In [48]:
bm25_scores = bm25.get_scores(tokenized_query)

In [49]:
bm25_scores

array([0.1907998 , 0.16686672, 0.17803252, 0.        ])

In [62]:
sorted_indices2 = np.argsort(bm25_scores)[::-1]

In [63]:
sorted_indices2

array([0, 2, 1, 3])

In [79]:
top_4_documents

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [56]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [80]:
reranked_documents = [(top_4_documents[i], bm25_scores[i]) for i in sorted_indices2]

In [81]:
reranked_documents

[('Efficient keyword extraction enhances search accuracy.',
  0.19079979534096053),
 ('Understanding document structure aids in keyword extraction.',
  0.1780325227902643),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  0.1668667199671815),
 ('Document analysis involves extracting keywords.', 0.0)]

In [82]:
print("Rerank of top 4 Documents:")
for rank, (document, similarity) in enumerate(reranked_documents, start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Rerank of top 4 Documents:
Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.19079979534096053
Rank 2: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.1780325227902643
Rank 3: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.1668667199671815
Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.0


In [84]:
ranked_documents[:4]

[('Efficient keyword extraction enhances search accuracy.', 0.7521413),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  0.74481654),
 ('Understanding document structure aids in keyword extraction.', 0.6316117),
 ('Document analysis involves extracting keywords.', 0.56756926)]

# Cross-Encoder

In [85]:
from sentence_transformers import CrossEncoder

In [86]:
cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [95]:
top_4_documents

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [96]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [97]:
pairs = []
for doc in top_4_documents:
    pairs.append([query, doc])

In [127]:
pairs

[['Natural language processing techniques enhance keyword extraction efficiency.',
  'Efficient keyword extraction enhances search accuracy.'],
 ['Natural language processing techniques enhance keyword extraction efficiency.',
  'Machine learning algorithms can optimize keyword extraction methods.'],
 ['Natural language processing techniques enhance keyword extraction efficiency.',
  'Understanding document structure aids in keyword extraction.'],
 ['Natural language processing techniques enhance keyword extraction efficiency.',
  'Document analysis involves extracting keywords.']]

In [128]:
scores = cross_encoder.predict(pairs)
scores

array([ 3.1378722,  0.842167 , -2.919299 , -2.8781896], dtype=float32)

In [129]:
scored_docs = zip(scores, top_4_documents)

In [130]:
scored_docs

In [131]:
reranked_document_cross_encoder = sorted(scored_docs, reverse=True)

In [132]:
reranked_document_cross_encoder

[(3.1378722, 'Efficient keyword extraction enhances search accuracy.'),
 (0.842167,
  'Machine learning algorithms can optimize keyword extraction methods.'),
 (-2.8781896, 'Document analysis involves extracting keywords.'),
 (-2.919299, 'Understanding document structure aids in keyword extraction.')]

# BM_25

In [110]:
reranked_documents

[('Efficient keyword extraction enhances search accuracy.',
  0.19079979534096053),
 ('Understanding document structure aids in keyword extraction.',
  0.1780325227902643),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  0.1668667199671815),
 ('Document analysis involves extracting keywords.', 0.0)]

In [111]:
!pip install cohere

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.8/169.8 kB 1.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.3/139.3 kB 7.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 21.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 9.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 57.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 42.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.2/82.2 kB 12.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 10.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 8.8 MB/s eta 0:00:00
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.19.1
    Uninstalling tokenizers-0.19.1:
      Successfully uninstalled tokenizers-0.19.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installe

In [112]:
import cohere

In [113]:
co = cohere.Client("nbDqU1hTVxWmXGbLYI6OnYhp4Cx40MZ5hOmO5oKX")

In [116]:
top_4_documents

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [117]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [118]:
response = co.rerank(
    model="rerank-english-v3.0",
    query="Natural language processing techniques enhance keyword extraction efficiency.",
    documents=top_4_documents,
    return_documents=True
)

In [119]:
print(response)

id='41dcfeb5-fada-41a0-8119-7860e3cc80fc' results=[RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Efficient keyword extraction enhances search accuracy.'), index=0, relevance_score=0.99411184), RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Machine learning algorithms can optimize keyword extraction methods.'), index=1, relevance_score=0.9129032), RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Understanding document structure aids in keyword extraction.'), index=2, relevance_score=0.32885265), RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Document analysis involves extracting keywords.'), index=3, relevance_score=0.02865267)] meta=ApiMeta(api_version=ApiMetaApiVersion(version='1', is_deprecated=None, is_experimental=None), billed_units=ApiMetaBilledUnits(input_tokens=None, output_tokens=None, search_units=1, classifications=None), tokens=None, warnings=None)


In [120]:
response.results[0].document.text

'Efficient keyword extraction enhances search accuracy.'

In [121]:
response.results[0].relevance_score

0.99411184

In [122]:
for i in range(4):
  print(f'text: {response.results[i].document.text} score: {response.results[i].relevance_score}')

text: Efficient keyword extraction enhances search accuracy. score: 0.99411184
text: Machine learning algorithms can optimize keyword extraction methods. score: 0.9129032
text: Understanding document structure aids in keyword extraction. score: 0.32885265
text: Document analysis involves extracting keywords. score: 0.02865267
